disabled_rules: # rule identifiers to exclude from running
- vertical_whitespace
- trailing_whitespace
- trailing_comma
- closure_parameter_position
- type_name
- nesting
- identifier_name

opt_in_rules: # some rules are only opt-in
# Find all the available rules by running:
# swiftlint rules
- closure_spacing
- yoda_condition

included: # paths to include during linting. `--path` is ignored if present.
- Itinerary

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods

- UnitTests
- UITests
- Frameworks

analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
- explicit_self

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
line_length: 160
